name = "script-hub"
main = "src/index.js"
compatibility_date = "2024-03-20"

[site]
bucket = "./public"

[[kv_namespaces]]
binding = "SCRIPT_STATS"
id = "2f33b505e6a34491a64e12c7c21e94e5" # 您需要在 Cloudflare Dashboard 创建并替换此 ID
