name = "script-workers"
main = "src/index.js"
compatibility_date = "2025-09-30"

[site]
bucket = "./public"

[[kv_namespaces]]
binding = "KV"
id = "2f33b505e6a34491a64e12c7c21e94e5" # 替换为您的生产环境 KV 命名空间 ID