name = "script-hub"
main = "src/index.js"
compatibility_date = "2024-03-20"

[assets]
directory = "./public/"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB" # 代码中使用的名字
database_name = "script-hub" # 您创建的数据库名
database_id = "b81dd067-dc8f-48f8-8ab9-f711bcbf244c" # <--- 请在这里粘贴您 D1 数据库的实际 ID
