# ===================================================================
# PowerShell Script to Setup API Wallpaper
# Function: Guides user for API URL and refresh interval, then creates a scheduled task.
# ===================================================================

# --- 1. Welcome ---
Clear-Host
Write-Host "=============================================" -ForegroundColor Green
Write-Host "  Welcome to the API Wallpaper Setup Script!" -ForegroundColor Green
Write-Host "============================================="
Write-Host "This script will help you with the following:"
Write-Host "  1. Create a PowerShell script to download and set the wallpaper."
Write-Host "  2. Create a Windows Scheduled Task to run the script periodically."
Write-Host ""

# --- 2. User Input ---
# Get API URL
$defaultApiUrl = "https://api.sqmn.eu.org/wallpaper/random"
$apiUrl = ""
while ($true) {
    $userInput = Read-Host "> Enter API URL (or press Enter for default)"
    if ([string]::IsNullOrWhiteSpace($userInput)) {
        $apiUrl = $defaultApiUrl
        Write-Host "  Using default URL: $apiUrl"
        break
    }
    if ($userInput -like "http*") {
        $apiUrl = $userInput
        break
    }
    Write-Warning "Invalid URL format. Please enter a valid URL starting with http or https."
}

# Get refresh interval
$intervalMinutes = 0
while ($intervalMinutes -le 0) {
    try {
        $input = Read-Host "> Please enter the refresh interval in minutes (e.g., 60)"
        $intervalMinutes = [int]$input
        if ($intervalMinutes -le 0) {
            Write-Warning "Please enter an integer greater than 0."
        }
    }
    catch {
        Write-Warning "Invalid input. Please enter a number."
        $intervalMinutes = 0
    }
}

Write-Host ""
Write-Host "Configuration Summary:" -ForegroundColor Cyan
Write-Host "  API URL: $apiUrl"
Write-Host "  Refresh Interval: $intervalMinutes minutes"
Write-Host ""

# --- 3. Define Paths and Script Content ---
$scriptDirectory = "$env:USERPROFILE\Documents\AutoApiWallpaper"
if (-not (Test-Path $scriptDirectory)) {
    New-Item -ItemType Directory -Path $scriptDirectory | Out-Null
}

$wallpaperScriptPath = Join-Path $scriptDirectory "Set-ApiWallpaper.ps1"
$imagePath = Join-Path $scriptDirectory "api_wallpaper.jpg"

# C# code for setting wallpaper.
$csharpCode = @'
using System.Runtime.InteropServices;
public class Wallpaper {
    [DllImport("user32.dll", CharSet = CharSet.Auto)]
    public static extern int SystemParametersInfo(int uAction, int uParam, string lpvParam, int fuWinIni);
    public static void Set(string path) {
        SystemParametersInfo(20, 0, path, 3);
    }
}
'@

# Build the content for the child script using the -f format operator.
$wallpaperScriptContent = @"
# Wallpaper Setting Script - Generated by Setup-ApiWallpaper.ps1

try {{
    # Download image from API
    Invoke-WebRequest -Uri "{0}" -OutFile "{1}" -UseBasicParsing

    # Set wallpaper
    \$code = @'
{2}
'@
    Add-Type -TypeDefinition \$code
    [Wallpaper]::Set("{1}")
}}
catch {{
    # Error logging can be added here.
}}
"@ -f $apiUrl, $imagePath, $csharpCode

# Write the child script to a file
Set-Content -Path $wallpaperScriptPath -Value $wallpaperScriptContent -Encoding UTF8

Write-Host "Successfully created wallpaper script: $wallpaperScriptPath" -ForegroundColor Green

# --- 4. Create Windows Scheduled Task ---
$taskName = "Auto API Wallpaper Changer"
$taskDescription = "Fetches a new image from API and sets it as wallpaper every $intervalMinutes minutes."
$action = New-ScheduledTaskAction -Execute "powershell.exe" -Argument "-ExecutionPolicy Bypass -File `"$wallpaperScriptPath`""
$trigger = New-ScheduledTaskTrigger -Once -At (Get-Date) -RepetitionInterval (New-TimeSpan -Minutes $intervalMinutes)
$settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable -ExecutionTimeLimit (New-TimeSpan -Minutes 5)

# Check for and remove old task to prevent duplicates
if (Get-ScheduledTask -TaskName $taskName -ErrorAction SilentlyContinue) {
    Unregister-ScheduledTask -TaskName $taskName -Confirm:$false
    Write-Host "  Old task found and updated." -ForegroundColor Yellow
}

Register-ScheduledTask -TaskName $taskName -Action $action -Trigger $trigger -Settings $settings -Description $taskDescription -User $env:USERNAME

Write-Host "Successfully created Windows Scheduled Task: '$taskName'" -ForegroundColor Green
Write-Host ""
Write-Host "All done! The wallpaper will change for the first time in about a minute."
Write-Host "To modify or remove, open 'Task Scheduler' and find '$taskName'."
Write-Host ""
Read-Host "Press Enter to exit..."
